# Alacritty Terminal Configuration
# Converted from Ghostty configuration

[window]
opacity = 0.9
decorations = "full"
dynamic_title = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 11

[cursor]
style = { shape = "Block", blinking = "Off" }

[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/nu"

[colors]
# Catppuccin Mocha theme
primary = { background = "#1e1e2e", foreground = "#cdd6f4" }
normal = { black = "#45475a", red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af", blue = "#89b4fa", magenta = "#f5c2e7", cyan = "#94e2d5", white = "#bac2de" }
bright = { black = "#585b70", red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af", blue = "#89b4fa", magenta = "#f5c2e7", cyan = "#94e2d5", white = "#a6adc8" }

[keyboard]
# Standard keybindings similar to Ghostty
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "W", mods = "Control|Shift", action = "Quit" },
]

[terminal]
